### ISSUE TITLE
f

### ISSUE THREAD

**Issue by feresum** [ConorOBrien-Foxx/Comm#3]
# `f`: Change programming paradigm from stack-based to functional

Some users may not want to do stack-based programming. They can get a different programming paradigm with the `f` command. A meta advantage of this command is that users will have 256+ new chances to assign commands, as the stack-based commands are obsolete after `f` has been used.

**Comment by ConorOBrien-Foxx** [comment]
"Functional" paradigm - as in, what?

**Comment by feresum** [comment]
https://en.wikipedia.org/wiki/Functional_programming

**Comment by ConorOBrien-Foxx** [comment]
Ah, I see.
